kind: Deployment
apiVersion: apps/v1
metadata:
# set your lab user name
  name: {{ .Chart.Name }} # user12-hello-world
spec:
  replicas: {{ .Values.ReplicaNumber }} # 3
  selector:
    matchLabels:
# set your lab user name
      app: {{ .Chart.Name }} # user12-hello-world
  template:
    metadata:
      labels:
# set your lab user name
        app: {{ .Chart.Name }} # user12-hello-world
    spec:
      volumes:
        - name: index-html
          configMap:
            name: '{{ .Chart.Name }}-html'
            defaultMode: 420
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: {{ .Chart.Name }} # hello-world
          ports:
            - containerPort: {{ .Values.containers.containerPort }} # 8080
              protocol: TCP
          imagePullPolicy: IfNotPresent
# Update with the image you build in part 1
          image: {{ .Values.containers.image }}:{{ .Values.containers.tag }} # 'quay.io/edi-redhat/web-rh-workshop:v2'
          volumeMounts:
          - name: index-html
            mountPath: /tmp/html # this will mount the html.index file to it application location
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10