kind: Service
apiVersion: v1
metadata:
# set your user name
  name: {{ .Chart.Name }}-service # user12-hello-world
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.service.servicePort }} # 8080
      targetPort: {{ .Values.containers.containerPort }} # 8080
  selector:
# set your user name
    app: {{ .Chart.Name }} # user12-hello-world